var modules =
[
    [ "Basic Math Functions", "da/de5/group__group_math.html", null ],
    [ "Fast Math Functions", "d0/d39/group__group_fast_math.html", "d0/d39/group__group_fast_math" ],
    [ "Complex Math Functions", "d4/d81/group__group_cmplx_math.html", null ],
    [ "Filtering Functions", "d2/dab/group__group_filters.html", null ],
    [ "Matrix Functions", "dd/d0e/group__group_matrix.html", null ],
    [ "Transform Functions", "d1/dd4/group__group_transforms.html", null ],
    [ "Controller Functions", "d1/d78/group__group_controller.html", "d1/d78/group__group_controller" ],
    [ "Statistics Functions", "d4/d50/group__group_stats.html", null ],
    [ "Support Functions", "d7/d01/group__group_support.html", null ],
    [ "Interpolation Functions", "de/d4e/group__group_interpolation.html", "de/d4e/group__group_interpolation" ],
    [ "Examples", "d0/ddf/group__group_examples.html", null ],
    [ "Bluetooth", "df/d6f/group___bluetooth.html", "df/d6f/group___bluetooth" ],
    [ "Cycling Speed and Cadence Service feature bits", "de/db0/group___b_l_e___c_s_c_s___f_e_a_t_u_r_e_s.html", "de/db0/group___b_l_e___c_s_c_s___f_e_a_t_u_r_e_s" ],
    [ "HID Keyboard modifier key bits", "da/d9d/group___h_i_d___m_o_d_i_f_i_e_r___k_e_y_s.html", "da/d9d/group___h_i_d___m_o_d_i_f_i_e_r___k_e_y_s" ],
    [ "HID Keyboard LEDs bits", "de/df6/group___h_i_d___k_b___l_e_d_s.html", "de/df6/group___h_i_d___k_b___l_e_d_s" ],
    [ "Enumerations", "db/dff/group___enumerations.html", "db/dff/group___enumerations" ],
    [ "Miscellaneous", "d8/d7e/group___miscellaneous.html", "d8/d7e/group___miscellaneous" ],
    [ "Peripherals", "d1/d6c/group___peripherals.html", "d1/d6c/group___peripherals" ],
    [ "RTOS", "d8/dba/group___r_t_o_s.html", "d8/dba/group___r_t_o_s" ],
    [ "CMSIS Global Defines", "d6/d7e/group___c_m_s_i_s__glob__defs.html", null ],
    [ "Defines and Type Definitions", "d8/dcb/group___c_m_s_i_s__core__register.html", "d8/dcb/group___c_m_s_i_s__core__register" ],
    [ "Functions and Instructions Reference", "da/db5/group___c_m_s_i_s___core___function_interface.html", "da/db5/group___c_m_s_i_s___core___function_interface" ],
    [ "CMSIS Core Instruction Interface", "d5/d02/group___c_m_s_i_s___core___instruction_interface.html", null ]
];